[options]
admin_passwd = admin_pwd
addons_path = /path/custom-addons
csv_internal_sep = ,

db_host = 127.0.0.1 ;localhost
db_port = 6432 ;5432
db_user = kokai
db_password = admin_pwd
db_maxconn = 30
pg_path =

;dev_mode = reload
http_port = 8069
http_enable = True
http_interface =
xmlrpcs_interfaces = 0.0.0.0
xmlrpc_port = 8069
db_sslmode = prefer
dbfilter = .*
db_template = template0
proxy_mode = True
gevent_port = 8072
longpolling_port = 8072

log_db = False
log_db_level = warning
log_handler = :INFO
log_level = info

transient_age_limit = 60
limit_memory_hard = 2684354560
limit_memory_soft = 2147483648
limit_time_real = 640000
limit_time_cpu = 640000

translate_modules = ['all']
logfile = /var/log/kokai/kokai.log
workers = 2
