[databases]
# Format: nama_db = host=ADDR port=PORT auth_user=USER
# Gunakan '*' agar PgBouncer otomatis meneruskan semua database odoo
* = host=127.0.0.1 port=5432

[pgbouncer]
listen_addr = 127.0.0.1
listen_port = 6432
auth_type = scram-sha-256
auth_file = /etc/pgbouncer/userlist.txt
admin_users = postgres
pidfile = /run/pgbouncer/pgbouncer.pid
unix_socket_dir = /run/pgbouncer

# MODE POOLING (Sangat Penting untuk Odoo)
pool_mode = transaction

# Batasan Koneksi
max_client_conn = 1000
default_pool_size = 50
min_pool_size = 10
reserve_pool_size = 5
logfile = /var/log/pgbouncer/pgbouncer.log
